{
 "title": "DefectDojo Exporter",
 "tags": [ "defectdojo" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "product",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active,product_name)"
    }
   },
   {
    "name": "severity",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active,severity)"
    }
   },
   {
    "name": "cwe",
    "query": {
     "query": "label_values(dojo_vulnerabilities_active{product=~\"$product\"},cwe)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_active{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Duplicate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_duplicate{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "False Positive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(product, severity)  (dojo_vulnerabilities_false_positive{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Out Of Scope",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_out_of_scope{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Risk Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_risk_accepted{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Under Review",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(product, severity)  (dojo_vulnerabilities_under_review{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Verified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_verified{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Mitigated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(product, severity) (dojo_vulnerabilities_mitigated{product=~\"$product\", severity=~\"$severity\", cwe=~\"$cwe\"})",
     "legendFormat": "{{product}} - {{severity}}"
    }
   ]
  }
 ]
}